# Generated by Django 3.0.3 on 2020-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.IntegerField(choices=[(0, "Don't Show on Gallery Page"), (1, 'Show on Gallery Page')], default=1),
        ),
    ]
