# Generated by Django 3.0.3 on 2020-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200410_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoforgallery',
            name='status',
            field=models.IntegerField(choices=[(0, 'not in home gallery'), (1, 'in home gallery')], default=0),
        ),
    ]
