# Generated by Django 3.0.3 on 2020-03-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
    ]
