# Generated by Django 3.0.3 on 2020-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_gallery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='logo.png', upload_to='gallery')),
            ],
        ),
    ]
