# Generated by Django 3.0.3 on 2020-03-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_photoforgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoforgallery',
            name='gallery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Gallery'),
            preserve_default=False,
        ),
    ]
